export default {
  DOC_LIMIT: 15,

  DOC_TITLE_LIMIT: 20,
  DOC_DESCRIPTION_LIMIT: 200,
  
  DOC_NAVIGATION_TITLE_LIMIT: 20,
  DOC_NAVIGATION_SUB_TITLE_LIMIT: 25,
  DOC_INDEXES_TABLE_TITLE_LIMIT: 25,

  DOC_CATEGORY_LIMIT: 15,

  DOC_PAGE_LIMIT: 50,
  DOC_PAGE_TEXT_LIMIT: 35000,

  DOC_CUSTOMIZATIONS_LIMIT: 5,
  DOC_CUSTOMIZATION_TEXT_LIMIT: 50000,

  EDITOR_AUTOSAVE_AFTER_STOP_TYPING_INTERVAL: 500,
  EDITOR_AUTOSAVE_INTERVAL: 2000
};